USE [master]
GO

-- Crear los logins si no existen
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'Nestor')
BEGIN
    CREATE LOGIN [Nestor] WITH PASSWORD = N'tu_contraseña_aqui';
END
GO

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'Arlin')
BEGIN
    CREATE LOGIN [Arlin] WITH PASSWORD = N'tu_contraseña_aqui';
END
GO

-- Crear la base de datos con la nueva ruta
CREATE DATABASE [prograIII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prograIII', FILENAME = N'C:\SQLData\prograIII.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prograIII_log', FILENAME = N'C:\SQLData\prograIII_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

-- Ajustar el nivel de compatibilidad
ALTER DATABASE [prograIII] SET COMPATIBILITY_LEVEL = 130
GO

-- Habilitar el servicio de texto completo si está instalado
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [prograIII].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO

-- Configurar opciones de la base de datos
ALTER DATABASE [prograIII] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [prograIII] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [prograIII] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [prograIII] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [prograIII] SET ARITHABORT OFF 
GO
ALTER DATABASE [prograIII] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [prograIII] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [prograIII] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [prograIII] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [prograIII] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [prograIII] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [prograIII] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [prograIII] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [prograIII] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [prograIII] SET  DISABLE_BROKER 
GO
ALTER DATABASE [prograIII] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [prograIII] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [prograIII] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [prograIII] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [prograIII] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [prograIII] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [prograIII] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [prograIII] SET RECOVERY FULL 
GO
ALTER DATABASE [prograIII] SET  MULTI_USER 
GO
ALTER DATABASE [prograIII] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [prograIII] SET DB_CHAINING OFF 
GO
ALTER DATABASE [prograIII] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [prograIII] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [prograIII] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [prograIII] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [prograIII] SET QUERY_STORE = ON
GO
ALTER DATABASE [prograIII] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

-- Usar la base de datos
USE [prograIII]
GO

-- Crear usuarios
CREATE USER [Nestor_1] FOR LOGIN [Nestor] WITH DEFAULT_SCHEMA=[dbo]
GO
CREATE USER [Arlin_1] FOR LOGIN [Arlin] WITH DEFAULT_SCHEMA=[dbo]
GO

-- Asignar roles a los usuarios
ALTER ROLE [db_owner] ADD MEMBER [Nestor_1]
GO
ALTER ROLE [db_owner] ADD MEMBER [Arlin_1]
GO

-- Crear tablas
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estados](
    [Estado] [numeric](1, 0) NOT NULL,
    [Descripcion_estado] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Estados] PRIMARY KEY CLUSTERED 
(
    [Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Roles](
    [Rol] [numeric](1, 0) NOT NULL,
      NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
    [Rol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Usuarios](
    [Codigo] [numeric](18, 0) NOT NULL,
      NOT NULL,
      NOT NULL,
      NOT NULL,
    [Rol] [numeric](1, 0) NOT NULL,
    [Estado] [numeric](1, 0) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
    [Codigo] ASC,
    [Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Crear relaciones de las tablas
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Estados] FOREIGN KEY([Estado])
REFERENCES [dbo].[Estados] ([Estado])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Estados]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Roles] FOREIGN KEY([Rol])
REFERENCES [dbo].[Roles] ([Rol])
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Roles]
GO

-- Asegurarse que la base de datos esté en modo de lectura y escritura
USE [master]
GO
ALTER DATABASE [prograIII] SET  READ_WRITE 
GO
